=== nparvez71/NetbeanSoftware/firoza_project/src/com/google/swing/xml/Family.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/Family.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE Family SYSTEM "Family.dtd">

    <Family>
    ...
    </Family>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Family (Members)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Members (name|gifts)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT gifts (#PCDATA)>

=== nparvez71/NetbeanSoftware/firoza_project/src/com/google/swing/xml/Family.xml
<?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE Family SYSTEM "Family.dtd">



<Family>
  <Members>
    <name> Bhaia   </name> 
    <gifts> Panjabi  </gifts> 
       
  </Members>  
    
    
  <Members>
    <name>Rezaul Bhaia   </name> 
    <gifts> Shirt  </gifts> 
       
  </Members>  
      
  <Members>
    <name> Tashbeed   </name> 
    <gifts> T-shirt  </gifts> 
       
  </Members>  
      
   <Members>
    <name> Hashi   </name> 
    <gifts> Salwar-kamij  </gifts> 
       
  </Members>  
     
   <Members>
    <name> Tahzeeb   </name> 
    <gifts> Scurt  </gifts> 
       
  </Members>  
     
</Family>
