=== nparvez71/NetbeanSoftware/firoza_project/build/classes/com/google/swing/xml/StudentsAdd.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/StudentsAdd.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE Students SYSTEM "StudentsAdd.dtd">

    <Students>
    ...
    </Students>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Students (Student)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Student (name|id|age|email)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT id (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT age (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT email (#PCDATA)>

=== nparvez71/NetbeanSoftware/firoza_project/build/classes/com/google/swing/xml/StudentsAdd.xml
<?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE Students SYSTEM "StudentsAdd.dtd">



<Students>
    <Student>
     <name>firoza</name> 
        <id>1001</id>
        <age>27</age>
        <email>firozaajahan@gmail.com</email> 
       
    </Student>
    
     <Student>
     <name>firoza</name> 
        <id>1001</id>
        <age>27</age>
        <email>firozaajahan@gmail.com</email> 
       
    </Student>
    
</Students>
